packages:
  - apps/*
  - '!apps/ui-reference'
  - packages/*

onlyBuiltDependencies:
  - '@ffmpeg-installer/linux-x64'
  - better-sqlite3
  - esbuild
  - msgpackr-extract
  - onnxruntime-node
  - protobufjs
  - sharp
