/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FreeFormRouteImport } from './routes/free-form'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScenariosIndexRouteImport } from './routes/scenarios/index'
import { Route as HistoryIndexRouteImport } from './routes/history/index'
import { Route as SessionRoomNameRouteImport } from './routes/session/$roomName'
import { Route as HistorySessionIdRouteImport } from './routes/history/$sessionId'
import { Route as AdminScenariosRouteImport } from './routes/admin/scenarios'
import { Route as AdminKnowledgeItemsRouteImport } from './routes/admin/knowledge-items'
import { Route as ScenariosScenarioIdIndexRouteImport } from './routes/scenarios/$scenarioId/index'
import { Route as ScenariosScenarioIdPracticeRolePlayRouteImport } from './routes/scenarios/$scenarioId/practice/role-play'
import { Route as ScenariosScenarioIdPracticeFreeFormRouteImport } from './routes/scenarios/$scenarioId/practice/free-form'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeFormRoute = FreeFormRouteImport.update({
  id: '/free-form',
  path: '/free-form',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenariosIndexRoute = ScenariosIndexRouteImport.update({
  id: '/scenarios/',
  path: '/scenarios/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryIndexRoute = HistoryIndexRouteImport.update({
  id: '/history/',
  path: '/history/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionRoomNameRoute = SessionRoomNameRouteImport.update({
  id: '/session/$roomName',
  path: '/session/$roomName',
  getParentRoute: () => rootRouteImport,
} as any)
const HistorySessionIdRoute = HistorySessionIdRouteImport.update({
  id: '/history/$sessionId',
  path: '/history/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminScenariosRoute = AdminScenariosRouteImport.update({
  id: '/admin/scenarios',
  path: '/admin/scenarios',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminKnowledgeItemsRoute = AdminKnowledgeItemsRouteImport.update({
  id: '/admin/knowledge-items',
  path: '/admin/knowledge-items',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenariosScenarioIdIndexRoute =
  ScenariosScenarioIdIndexRouteImport.update({
    id: '/scenarios/$scenarioId/',
    path: '/scenarios/$scenarioId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ScenariosScenarioIdPracticeRolePlayRoute =
  ScenariosScenarioIdPracticeRolePlayRouteImport.update({
    id: '/scenarios/$scenarioId/practice/role-play',
    path: '/scenarios/$scenarioId/practice/role-play',
    getParentRoute: () => rootRouteImport,
  } as any)
const ScenariosScenarioIdPracticeFreeFormRoute =
  ScenariosScenarioIdPracticeFreeFormRouteImport.update({
    id: '/scenarios/$scenarioId/practice/free-form',
    path: '/scenarios/$scenarioId/practice/free-form',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/free-form': typeof FreeFormRoute
  '/login': typeof LoginRoute
  '/admin/knowledge-items': typeof AdminKnowledgeItemsRoute
  '/admin/scenarios': typeof AdminScenariosRoute
  '/history/$sessionId': typeof HistorySessionIdRoute
  '/session/$roomName': typeof SessionRoomNameRoute
  '/history/': typeof HistoryIndexRoute
  '/scenarios/': typeof ScenariosIndexRoute
  '/scenarios/$scenarioId/': typeof ScenariosScenarioIdIndexRoute
  '/scenarios/$scenarioId/practice/free-form': typeof ScenariosScenarioIdPracticeFreeFormRoute
  '/scenarios/$scenarioId/practice/role-play': typeof ScenariosScenarioIdPracticeRolePlayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/free-form': typeof FreeFormRoute
  '/login': typeof LoginRoute
  '/admin/knowledge-items': typeof AdminKnowledgeItemsRoute
  '/admin/scenarios': typeof AdminScenariosRoute
  '/history/$sessionId': typeof HistorySessionIdRoute
  '/session/$roomName': typeof SessionRoomNameRoute
  '/history': typeof HistoryIndexRoute
  '/scenarios': typeof ScenariosIndexRoute
  '/scenarios/$scenarioId': typeof ScenariosScenarioIdIndexRoute
  '/scenarios/$scenarioId/practice/free-form': typeof ScenariosScenarioIdPracticeFreeFormRoute
  '/scenarios/$scenarioId/practice/role-play': typeof ScenariosScenarioIdPracticeRolePlayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/free-form': typeof FreeFormRoute
  '/login': typeof LoginRoute
  '/admin/knowledge-items': typeof AdminKnowledgeItemsRoute
  '/admin/scenarios': typeof AdminScenariosRoute
  '/history/$sessionId': typeof HistorySessionIdRoute
  '/session/$roomName': typeof SessionRoomNameRoute
  '/history/': typeof HistoryIndexRoute
  '/scenarios/': typeof ScenariosIndexRoute
  '/scenarios/$scenarioId/': typeof ScenariosScenarioIdIndexRoute
  '/scenarios/$scenarioId/practice/free-form': typeof ScenariosScenarioIdPracticeFreeFormRoute
  '/scenarios/$scenarioId/practice/role-play': typeof ScenariosScenarioIdPracticeRolePlayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/free-form'
    | '/login'
    | '/admin/knowledge-items'
    | '/admin/scenarios'
    | '/history/$sessionId'
    | '/session/$roomName'
    | '/history/'
    | '/scenarios/'
    | '/scenarios/$scenarioId/'
    | '/scenarios/$scenarioId/practice/free-form'
    | '/scenarios/$scenarioId/practice/role-play'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/free-form'
    | '/login'
    | '/admin/knowledge-items'
    | '/admin/scenarios'
    | '/history/$sessionId'
    | '/session/$roomName'
    | '/history'
    | '/scenarios'
    | '/scenarios/$scenarioId'
    | '/scenarios/$scenarioId/practice/free-form'
    | '/scenarios/$scenarioId/practice/role-play'
  id:
    | '__root__'
    | '/'
    | '/free-form'
    | '/login'
    | '/admin/knowledge-items'
    | '/admin/scenarios'
    | '/history/$sessionId'
    | '/session/$roomName'
    | '/history/'
    | '/scenarios/'
    | '/scenarios/$scenarioId/'
    | '/scenarios/$scenarioId/practice/free-form'
    | '/scenarios/$scenarioId/practice/role-play'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FreeFormRoute: typeof FreeFormRoute
  LoginRoute: typeof LoginRoute
  AdminKnowledgeItemsRoute: typeof AdminKnowledgeItemsRoute
  AdminScenariosRoute: typeof AdminScenariosRoute
  HistorySessionIdRoute: typeof HistorySessionIdRoute
  SessionRoomNameRoute: typeof SessionRoomNameRoute
  HistoryIndexRoute: typeof HistoryIndexRoute
  ScenariosIndexRoute: typeof ScenariosIndexRoute
  ScenariosScenarioIdIndexRoute: typeof ScenariosScenarioIdIndexRoute
  ScenariosScenarioIdPracticeFreeFormRoute: typeof ScenariosScenarioIdPracticeFreeFormRoute
  ScenariosScenarioIdPracticeRolePlayRoute: typeof ScenariosScenarioIdPracticeRolePlayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-form': {
      id: '/free-form'
      path: '/free-form'
      fullPath: '/free-form'
      preLoaderRoute: typeof FreeFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios/': {
      id: '/scenarios/'
      path: '/scenarios'
      fullPath: '/scenarios/'
      preLoaderRoute: typeof ScenariosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/': {
      id: '/history/'
      path: '/history'
      fullPath: '/history/'
      preLoaderRoute: typeof HistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$roomName': {
      id: '/session/$roomName'
      path: '/session/$roomName'
      fullPath: '/session/$roomName'
      preLoaderRoute: typeof SessionRoomNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/$sessionId': {
      id: '/history/$sessionId'
      path: '/history/$sessionId'
      fullPath: '/history/$sessionId'
      preLoaderRoute: typeof HistorySessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/scenarios': {
      id: '/admin/scenarios'
      path: '/admin/scenarios'
      fullPath: '/admin/scenarios'
      preLoaderRoute: typeof AdminScenariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/knowledge-items': {
      id: '/admin/knowledge-items'
      path: '/admin/knowledge-items'
      fullPath: '/admin/knowledge-items'
      preLoaderRoute: typeof AdminKnowledgeItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios/$scenarioId/': {
      id: '/scenarios/$scenarioId/'
      path: '/scenarios/$scenarioId'
      fullPath: '/scenarios/$scenarioId/'
      preLoaderRoute: typeof ScenariosScenarioIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios/$scenarioId/practice/role-play': {
      id: '/scenarios/$scenarioId/practice/role-play'
      path: '/scenarios/$scenarioId/practice/role-play'
      fullPath: '/scenarios/$scenarioId/practice/role-play'
      preLoaderRoute: typeof ScenariosScenarioIdPracticeRolePlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios/$scenarioId/practice/free-form': {
      id: '/scenarios/$scenarioId/practice/free-form'
      path: '/scenarios/$scenarioId/practice/free-form'
      fullPath: '/scenarios/$scenarioId/practice/free-form'
      preLoaderRoute: typeof ScenariosScenarioIdPracticeFreeFormRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FreeFormRoute: FreeFormRoute,
  LoginRoute: LoginRoute,
  AdminKnowledgeItemsRoute: AdminKnowledgeItemsRoute,
  AdminScenariosRoute: AdminScenariosRoute,
  HistorySessionIdRoute: HistorySessionIdRoute,
  SessionRoomNameRoute: SessionRoomNameRoute,
  HistoryIndexRoute: HistoryIndexRoute,
  ScenariosIndexRoute: ScenariosIndexRoute,
  ScenariosScenarioIdIndexRoute: ScenariosScenarioIdIndexRoute,
  ScenariosScenarioIdPracticeFreeFormRoute:
    ScenariosScenarioIdPracticeFreeFormRoute,
  ScenariosScenarioIdPracticeRolePlayRoute:
    ScenariosScenarioIdPracticeRolePlayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
